//
//  NutshellBackgrounds.swift
//  ProjectName
//
//  Created by LAK on 9/8/15.
//  Copyright (c) 2015 Tidepool. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class NutshellBackgrounds : NSObject {

    //// Drawing Methods

    public class func drawSplash_background(#bkgroundsize: CGSize) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let topGreen = UIColor(red: 0.545, green: 0.773, blue: 0.247, alpha: 1.000)
        let bottomGrayyellow = UIColor(red: 0.757, green: 0.706, blue: 0.604, alpha: 1.000)

        //// Gradient Declarations
        let background = CGGradientCreateWithColors(CGColorSpaceCreateDeviceRGB(), [topGreen.CGColor, bottomGrayyellow.CGColor], [0, 1])

        //// Rectangle Drawing
        let rectangleRect = CGRectMake(0, 0, bkgroundsize.width, bkgroundsize.height)
        let rectanglePath = UIBezierPath(rect: rectangleRect)
        CGContextSaveGState(context)
        rectanglePath.addClip()
        CGContextDrawLinearGradient(context, background,
            CGPointMake(rectangleRect.midX, rectangleRect.minY),
            CGPointMake(rectangleRect.midX, rectangleRect.maxY),
            0)
        CGContextRestoreGState(context)
    }

    //// Generated Images

    public class func imageOfSplash_background(#bkgroundsize: CGSize) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(CGSizeMake(60, 120), false, 0)
            NutshellBackgrounds.drawSplash_background(bkgroundsize: bkgroundsize)

        let imageOfSplash_background = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return imageOfSplash_background
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
