//
//  NutshellStyles.swift
//  ProjectName
//
//  Created by LAK on 9/8/15.
//  Copyright (c) 2015 Tidepool. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class NutshellStyles : NSObject {

    //// Cache

    private struct Cache {
        static var darkBackground: UIColor = UIColor(red: 0.157, green: 0.098, blue: 0.275, alpha: 1.000)
        static var brightBackground: UIColor = UIColor(red: 0.384, green: 0.486, blue: 1.000, alpha: 1.000)
        static var listItemDeleteBackground: UIColor = UIColor(red: 0.965, green: 0.435, blue: 0.337, alpha: 1.000)
        static var tableLightBkgndColor: UIColor = UIColor(red: 0.949, green: 0.953, blue: 0.961, alpha: 1.000)
    }

    //// Colors

    public class var darkBackground: UIColor { return Cache.darkBackground }
    public class var brightBackground: UIColor { return Cache.brightBackground }
    public class var listItemDeleteBackground: UIColor { return Cache.listItemDeleteBackground }
    public class var tableLightBkgndColor: UIColor { return Cache.tableLightBkgndColor }

    //// Drawing Methods

    public class func drawCanvas1() {
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
