//  Copyright (c) 2015, Tidepool Project
//  All rights reserved.
//  Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
//  1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
//  2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class NutshellStyles : NSObject {

    //// Cache

    private struct Cache {
        static var darkBackground: UIColor = UIColor(red: 0.157, green: 0.098, blue: 0.275, alpha: 1.000)
        static var brightBackground: UIColor = UIColor(red: 0.384, green: 0.486, blue: 1.000, alpha: 1.000)
        static var listItemDeleteBackground: UIColor = UIColor(red: 0.965, green: 0.435, blue: 0.337, alpha: 1.000)
        static var tableLightBkgndColor: UIColor = UIColor(red: 0.949, green: 0.953, blue: 0.961, alpha: 1.000)
    }

    //// Colors

    public class var darkBackground: UIColor { return Cache.darkBackground }
    public class var brightBackground: UIColor { return Cache.brightBackground }
    public class var listItemDeleteBackground: UIColor { return Cache.listItemDeleteBackground }
    public class var tableLightBkgndColor: UIColor { return Cache.tableLightBkgndColor }

    //// Drawing Methods

    public class func drawCanvas1() {
    }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
